#!/bin/bash

if [ $EUID != 0 ]; then
    echo "kali-repo must be sudo'd or ran as root!"
    exit 1
fi

if [ $# -ne 1 ]; then
    echo "Only takes one arg: [enable|disable]"
    exit 1
fi

REPO=/etc/apt/sources.list.d/kali.list

if ! [ -e $REPO ]; then
    echo "You have no kali source file!"
    exit 1
fi

case "$1" in
    enable )
        echo "Enabling kali repo for apt"
        tmp=`awk '{ if($1 ~ /^[#]/ ){ print $0 }}' $REPO`
        echo ${tmp#*#} >> $REPO.tmp
        mv $REPO.tmp $REPO
        apt update
    ;;

    disable )
        echo "Disabling kali repo for apt"
        awk '{ if($1 ~ /^[a-zA-Z]/){ print "#"$0 } }' $REPO >> $REPO.tmp
        mv $REPO.tmp $REPO
        apt update
    ;;
    check )
        awk '{ if($1 ~ /^[#]/){print "disabled"} else {print "enabled"}}' $REPO
esac
